### ISSUE TITLE
IDE plugin

### ISSUE THREAD

**Issue by theapache64** [theapache64/rebugger#1]
## Purpose
To generate `Rebugger` calls automatically

## Usage
- User presses `Alt + Enter` in editor 
- IDE shows an option called `Add Rebugger here`
- Selecting the option generates a Rebugger call that has all the args and states used in the composable

## Votes needed to start development
- 10

**Comment by theapache64** [comment]
Wow!! 30+ votes!! You guys got the deal! 👍  I'll start working on the plugin tomorrow 😄

**Comment by theapache64** [comment]
UPDATE: Development started : https://github.com/theapache64/rebugger-plugin/

**Comment by Akyongpogi28** [comment]
Please let me know if I'm not improving?

**Comment by theapache64** [comment]
@Akyongpogi28 On Weekdays I'll be mostly busy with office stuff. Major development will be happening on weekends or during free time.

**Comment by theapache64** [comment]
**UPDATE: First prototype**


https://user-images.githubusercontent.com/9678279/230740996-a47b93c2-e772-48fd-96ef-dde175822c7c.mov

**Comment by theapache64** [comment]
Here's the [first version](https://github.com/theapache64/rebugger-plugin/releases/tag/0.0.1) (`0.0.1`) of Rebugger Plugin.

https://user-images.githubusercontent.com/9678279/235495415-800925e8-ff09-45e4-b29f-b5365de8126e.mov

The next version will be published via JetBrains marketplace (https://github.com/theapache64/rebugger-plugin/issues/3)

NOTE: The above version has only basic analysis implemented. Future versions will cover more use cases :) 

Thanks for all the support folks 🙇
