### ISSUE TITLE
The latest version is not compatible with the older Kotlin version 

### ISSUE THREAD

**Issue by sudhirkhanger** [theapache64/rebugger#10]
Which version of Rebugger is supported on a project with Kotlin 1.7.10? Does the endpoint change as well?

**Comment by theapache64** [comment]
@sudhirkhanger We just moved from JitPack to mavenCentral. so yeah, the coordinates are changed 
![image](https://github.com/theapache64/rebugger/assets/9678279/68224675-3384-45a3-bbad-4d296d34ffbf)

Are you facing any issues with the new version ?

**Comment by theapache64** [comment]
@sudhirkhanger gentle reminder
