### ISSUE TITLE
The tag became System.out and no longer Rebugger after beta01, is this deliberate?

### ISSUE THREAD

**Issue by ravenfeld** [theapache64/rebugger#11]
The tag became System.out and no longer Rebugger after beta01, is this deliberate?

I made a simple `Log.e("TAG","message")` to show the concern with the tag
<img width="1203" alt="Capture d’écran 2023-12-14 à 09 25 05" src="https://github.com/theapache64/rebugger/assets/3765114/1c76349f-458b-4a58-8c9d-13df819f7004">

**Comment by theapache64** [comment]
Not deliberate. Which version ur using ?

**Comment by ravenfeld** [comment]
[1.0.0-rc01](https://github.com/theapache64/rebugger/releases/tag/1.0.0-rc01)

**Comment by theapache64** [comment]
Hmm.. interesting. It looks like the android variant is not published, and gradle is picking JVM variant, which relies on `System.out`. This will be fixed in rc02

**Comment by theapache64** [comment]
@ravenfeld `1.0.0-rc02` is available now. Can you check if it works ? :)

**Comment by ravenfeld** [comment]
Thank you very much, it works now.

And thank you for your bookshop, it helps me a lot to understand recomposition. I've learned that it's necessary to test in release because otherwise you'll get into recompositions that shouldn't be in debug.  

https://itnext.io/exercises-in-futility-jetpack-compose-recomposition-6ea3cf9bc1b4
