### ISSUE TITLE
Multiplatform Support

### ISSUE THREAD

**Issue by theapache64** [theapache64/rebugger#2]
**Problem**

- Currently `Rebugger` only supports Android. This ticket is to add support for Compose Multiplatform (`iOS, Android, Web, WASM and Desktop`)

**Votes needed to start development**

- 10

**Comment by pradeep-magzter** [comment]
please add multiplatform support for rebugger

**Comment by theapache64** [comment]
This is now in progress 🚀

**Comment by theapache64** [comment]
![image](https://github.com/theapache64/rebugger/assets/9678279/946ea6cb-4571-4d0f-8aab-8eb5c3a7d5b1)

This is surprising. For some reason, it still shows 404. I might be missing something. Debugging...

**Comment by theapache64** [comment]
Good news! We're live 

![image](https://github.com/theapache64/rebugger/assets/9678279/57a3f1cb-7551-4427-94e2-d30386c58961)

**Comment by theapache64** [comment]
Done. Turns out the commit itself can be considered as a migration guide 😄

![Uploading image.png…]()

**Comment by theapache64** [comment]
Alright folks. You can start using `1.0.0-rc01` with multiplatform support
